-- Portfolio App: Supabase/PostgreSQL schema
-- Run this once in Supabase Dashboard -> SQL Editor.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password_hash text not null,
  created_date timestamptz not null default now()
);
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  title text not null default '', description text not null default '', image_url text not null default '', category text not null default '', link text not null default '', order_index double precision not null default 0,
  created_date timestamptz not null default now(), updated_date timestamptz not null default now()
);
create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  client_name text not null default '', role text not null default '', quote text not null default '', rating double precision not null default 5, order_index double precision not null default 0,
  created_date timestamptz not null default now(), updated_date timestamptz not null default now()
);
create table if not exists public.site_settings (
  id bigint generated by default as identity primary key,
  hero_name text not null default '', hero_subtext text not null default '', cover_image_url text not null default '', about_text_1 text not null default '', about_text_2 text not null default '', resume_url text not null default '', email text not null default '', phone text not null default '', whatsapp text not null default '', location text not null default '', hourly_price text not null default '', hourly_features text not null default '', project_price text not null default '', project_features text not null default '', fulltime_price text not null default '', fulltime_features text not null default '',
  created_date timestamptz not null default now(), updated_date timestamptz not null default now()
);
create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  client_name text not null default '', client_email text not null default '', service text not null default '', date text not null default '', time text not null default '', message text not null default '', status text not null default 'pending',
  created_date timestamptz not null default now(), updated_date timestamptz not null default now()
);
create unique index if not exists uniq_booking_slot on public.bookings(date, time);
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null default '', email text not null default '', mode text not null default '', service text not null default '', message text not null default '',
  created_date timestamptz not null default now(), updated_date timestamptz not null default now()
);

alter table public.users enable row level security;
alter table public.projects enable row level security;
alter table public.testimonials enable row level security;
alter table public.site_settings enable row level security;
alter table public.bookings enable row level security;
alter table public.messages enable row level security;

insert into storage.buckets (id, name, public, file_size_limit)
values ('portfolio-uploads', 'portfolio-uploads', true, 10485760)
on conflict (id) do update set public = true, file_size_limit = 10485760;
